### ISSUE TITLE
Completed Assignment 3 (Penguins and Sanitation)

### ISSUE THREAD

**Issue by prasad-prerna** [ds4owd-001/md-03-assignments-prasad-prerna#1]
@larnsce @mianzg @sskorik01 I have completed both the assignments on Penguins and Sanitation.

**Comment by sskorik01** [comment]
Hi Prerna, 

Congratulations for working trough the module 3 assignments. It seems like you grasped the concepts from the course very well. Here are some small details:

1) You can check on the website how to change the pipe operator from %>%  to |> https://ds4owd-001.github.io/website/guide/

2) In part a), in the first part, the questions about the numbers of observations is asking the number of rows (should be 344 but you answered  2744) 

3) When you have several options for a variable such as

```{r}
 island=="Dream"|island=="Biscoe")
```
you can write it more easily as follows

```{r}
island %in% c("Dream", "Biscoe")
```
